# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build-unix-mac-win

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  POETRY_CACHE_DIR: ${{ github.workspace }}/.poetry_cache

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        
      - name: Install required version of Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2
          
      - name: Set up the cache
        uses: actions/cache@v3
        with:
          path: .poetry_cache
          key: tests-poetry-cache-v11-${{ matrix.os }}-py${{ matrix.python-version }}          
                  
      - name: Install project dependencies
        run: poetry install -vv || { rm -rf .poetry_cache/virtualenvs/*; poetry install -vv; }
        #run: poetry install -vv || { rm -rf .poetry_cache/*; poetry install -vv; }
        #run: poetry install -vv || { rm -rf .poetry_cache/virtualenvs/*; poetry cache clear repository --all; poetry install -vv; }
        
      - name: Run tests with Poetry
        run: poetry run pytest
